# springdoc-openapi项目配置
springdoc:
  api-docs:
    enabled: false
spring:
  # 数据源配置
  datasource:
    #    ==============Mysql==============
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbie3?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  #    ==============Pgsql==============
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/user_JNcKh5
  #    username: postgresql
  #    password: postgresql
  #    ==============Oracle==============
  #    driverClassName: oracle.jdbc.driver.OracleDriver
  #    url: jdbc:oracle:thin:@localhost:1521/orcl
  #    username: newbie
  #    password: newbie
  data:
    redis:
      host: localhost
      password:
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 1
newbie:
  # 日志
  weblog:
    enable: false
    default-strategy: all_api
    only-error: true
  # 验证码配置
  captcha:
    timeout: 60 #超时（单位：秒）
  # 文件服务配置
  file:
    scheme: default
    prefix: public
    # 本服务器文件保存磁盘地址
    file-location: /var/www/files
    # minio
    minio:
      end-point: http://localhost:9000
      access-key: upaGr2JF0uGD7dxpLzqM
      secret-key: NZvAgDfqr58OvcUrW9G942kmv4MSX40QTIuxTX0f
      bucket: files
sa-token:
  #  白名单
  white-list: /security/login, /security/initAdmin, /security/imageCaptcha, /public/**, /file/download
  # jwt秘钥
  jwt-secret-key: bsdasdasifhueuiwyurfewbfjsdafjg
  # token有效期半小时（单位：秒）
  timeout: 1800
  is-log: false